In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [6]:
statement_df = pd.DataFrame(
    { "Date" : [],
     "Item" : [],
     "Amount" : [],
     "Type" : [] } )

statement_df

Empty DataFrame
Columns: [Date, Item, Amount, Type]
Index: []

In [11]:
new_entry = pd.DataFrame(
    {"Date" : ["11th, January"],
     "Item" : ["Food"],
     "Amount" : [3000],
     "Type" : ["Expense"]}
)
statement_df = pd.concat([statement_df,new_entry] , ignore_index=True)

In [9]:
statement_df

            Date  Item  Amount     Type
0  11th, January  Food  3000.0  Expense

In [15]:
def add_transaction(current_df ,date,item,amount,types):
    new_entry = pd.DataFrame(
        {"Date" : [date],
         "Item" : [item],
         "Amount" : [amount],
         "Type" : [types] } )
    current_df = pd.concat([current_df,new_entry] , ignore_index=True)
    return current_df

In [17]:
df = add_transaction(statement_df,"Today","pizza",5000,"Expenses")
df

            Date   Item  Amount      Type
0  11th, January   Food  3000.0   Expense
1  11th, January   Food  3000.0   Expense
2          Today  pizza  5000.0  Expenses